In [3]:
import numpy as np 

import pandas as pd

In [4]:
crops = pd.read_csv("DATASET - Sheet1.csv")

potato_crop = crops

potato_crop.head()

CROP TYPE SOIL TYPE  REGION TEMPERATURE WEATHER CONDITION  WATER REQUIREMENT
0    BANANA       DRY  DESERT       10-20            NORMAL               8.75
1    BANANA       DRY  DESERT       10-20             SUNNY              10.25
2    BANANA       DRY  DESERT       10-20             WINDY               9.65
3    BANANA       DRY  DESERT       10-20             RAINY               0.75
4    BANANA       DRY  DESERT       20-30            NORMAL               9.85

In [5]:
potato_crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   CROP TYPE          2880 non-null   object 
 1   SOIL TYPE          2880 non-null   object 
 2   REGION             2880 non-null   object 
 3   TEMPERATURE        2880 non-null   object 
 4   WEATHER CONDITION  2880 non-null   object 
 5   WATER REQUIREMENT  2880 non-null   float64
dtypes: float64(1), object(5)
memory usage: 135.1+ KB


In [6]:
potato_crop.isnull().sum()

CROP TYPE            0
SOIL TYPE            0
REGION               0
TEMPERATURE          0
WEATHER CONDITION    0
WATER REQUIREMENT    0
dtype: int64

In [7]:
potato_crop.head()

CROP TYPE SOIL TYPE  REGION TEMPERATURE WEATHER CONDITION  WATER REQUIREMENT
0    BANANA       DRY  DESERT       10-20            NORMAL               8.75
1    BANANA       DRY  DESERT       10-20             SUNNY              10.25
2    BANANA       DRY  DESERT       10-20             WINDY               9.65
3    BANANA       DRY  DESERT       10-20             RAINY               0.75
4    BANANA       DRY  DESERT       20-30            NORMAL               9.85

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
object_columns = potato_crop.select_dtypes(include='object').columns
for col in object_columns:
    potato_crop[col] = le.fit_transform(potato_crop[col])

In [9]:
X = potato_crop.drop("WATER REQUIREMENT", axis = 1)

y = potato_crop["WATER REQUIREMENT"]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=42)

In [11]:
from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer



one = OneHotEncoder(handle_unknown = "ignore")

categorical_features = ["SOIL TYPE", "REGION", "WEATHER CONDITION"]

transformer = ColumnTransformer([("one", one, categorical_features)], remainder = "passthrough")



transformed_X_train = transformer.fit_transform(X_train)

transformed_X_train

array([[ 1.,  0.,  0., ...,  0., 11.,  3.],
       [ 0.,  1.,  0., ...,  0., 14.,  0.],
       [ 0.,  1.,  0., ...,  1.,  3.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  1.,  6.,  2.],
       [ 0.,  0.,  1., ...,  1.,  5.,  3.],
       [ 0.,  1.,  0., ...,  0., 10.,  3.]])

In [12]:
transformed_X_train.shape

(2304, 13)

In [13]:
X["WEATHER CONDITION"].value_counts()

WEATHER CONDITION
0    725
2    721
3    717
1    717
Name: count, dtype: int64

In [14]:
X["SOIL TYPE"].value_counts()

SOIL TYPE
0    960
1    960
2    960
Name: count, dtype: int64

In [15]:
X["REGION"].value_counts()

REGION
0    720
2    720
3    720
1    720
Name: count, dtype: int64

In [16]:
transformed_X_test = transformer.transform(X_test)

transformed_X_test

array([[ 0.,  1.,  0., ...,  0.,  2.,  1.],
       [ 0.,  1.,  0., ...,  0.,  3.,  3.],
       [ 0.,  1.,  0., ...,  0., 12.,  2.],
       ...,
       [ 0.,  0.,  1., ...,  1.,  8.,  3.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  7.,  0.]])

In [17]:
transformed_X_test.shape

(576, 13)

In [18]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(transformed_X_train, y_train)

model.score(transformed_X_test, y_test)*100

91.3637866617568

In [19]:
y_preds = model.predict(transformed_X_test)

y_preds

array([ 0.251     ,  7.4628    , 10.6607    ,  6.5271    ,  5.6446    ,
        0.195     ,  4.4758    ,  6.7697    ,  4.9434    ,  9.4446    ,
        3.869     ,  0.91125   ,  2.5808    ,  8.6644    , 11.934     ,
       20.427     ,  3.7602    ,  1.871     ,  0.4527    , 13.7845    ,
        6.3444    ,  7.5032    ,  5.6174    ,  0.8029    ,  7.9585    ,
        7.37805   ,  5.4492    ,  5.1158    , 11.3121    ,  5.8992    ,
        6.5789    , 10.2146    ,  8.1631    ,  0.61      ,  5.0522    ,
       13.9844    ,  0.107     ,  5.6193    ,  0.1       ,  1.63533333,
        7.5912    ,  3.7998    ,  5.9172    ,  8.7643    ,  8.4622    ,
        7.38615   ,  0.8865    ,  6.66      ,  7.19795   ,  9.1944    ,
        7.4572    ,  0.357     ,  5.7162    ,  8.4776    ,  3.7363    ,
        3.625     ,  2.5505    ,  8.7967    ,  0.119     ,  9.19995   ,
        8.3556    ,  5.6152    ,  8.436     ,  0.46325   ,  5.07315   ,
        4.18665   ,  7.7868    ,  5.0017    ,  4.8985    ,  5.55

In [20]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_preds)

mse

1.3838782801933824

In [21]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_preds)

mae

0.6410449363425924

In [22]:
from sklearn.metrics import r2_score

score = r2_score(y_test, y_preds)

score

0.9136378666175681

In [23]:
adjusted_r2 = 1 - (1-score)*(len(y_test)-1)/(len(y_test)-transformed_X_test.shape[1]-1)

adjusted_r2

0.9116401660233125

In [24]:
import joblib

joblib.dump(model, 'random_forest_model.joblib')


['random_forest_model.joblib']

In [25]:
import joblib

model = joblib.load('random_forest_model.joblib')


In [26]:
# استعراض الميزات المتوقعة من النموذج
print("Features expected by the model:", model.feature_names_in_)


AttributeError: 'RandomForestRegressor' object has no attribute 'feature_names_in_'